const $ = (s) => document.querySelector(s);
const els = {name:$('#locationName'),coords:$('#coords'),score:$('#score'),quality:$('#quality'),summary:$('#summary'),status:$('#statusText'),verdict:$('#verdict'),tonightCard:$('#tonightCard'),updated:$('#updatedText'),hourly:$('#hourly'),date:$('#forecastDate'),cloud:$('#cloudMetric'),activity:$('#activityMetric'),dark:$('#darkMetric'),places:$('#places'),sheet:$('#searchSheet'),backdrop:$('#sheetBackdrop'),input:$('#searchInput'),results:$('#searchResults'),hint:$('#searchHint'),toast:$('#toast'),forecastView:$('#forecastView'),mapView:$('#mapView'),placesView:$('#placesView'),mapNote:$('#mapNote'),bestWindow:$('#bestWindow'),viewMode:$('#viewMode'),directionText:$('#directionText'),directionArrow:$('#directionArrow'),kp:$('#kpValue'),bz:$('#bzValue'),confidence:$('#confidenceText'),infoSheet:$('#infoSheet'),detailBackdrop:$('#detailBackdrop'),infoTitle:$('#infoTitle'),infoValue:$('#infoValue'),infoBody:$('#infoBody'),tzNote:$('#tzNote')};
const FALLBACK={name:'Szczecin',country:'Polska',lat:53.4285,lon:14.5528,isDefault:true};
let saved=JSON.parse(localStorage.getItem('aurora-places')||'[]');
const NOAA_TTL=5*60*1000,REFRESH_EVERY=5*60*1000;
let loadSeq=0,mapLoc=null;
let current=null, auroraGrid=null, spaceWeather=null, timer, map, auroraLayer, locationMarker;
// Zamienia znaki specjalne HTML, żeby nazwy z zewnętrznych serwisów i localStorage nie były traktowane jak kod.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const fmtCoords=(lat,lon)=>`${Math.abs(lat).toFixed(2)}°${lat>=0?'N':'S'}  •  ${Math.abs(lon).toFixed(2)}°${lon>=0?'E':'W'}`;
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2200)}
function store(){localStorage.setItem('aurora-places',JSON.stringify(saved))}
function openSheet(){els.sheet.hidden=false;els.backdrop.hidden=false;setTimeout(()=>els.input.focus(),80)}
function closeSheet(){els.sheet.hidden=true;els.backdrop.hidden=true;els.input.value='';els.results.innerHTML='';els.hint.textContent='Wpisz co najmniej 2 znaki.'}
function switchView(name){const views={forecast:els.forecastView,map:els.mapView,places:els.placesView};Object.entries(views).forEach(([key,el])=>el.hidden=key!==name);[['homeBtn','forecast'],['mapBtn','map'],['savedBtn','places']].forEach(([id,key])=>$('#'+id).classList.toggle('active',key===name));if(name==='map')showMap();window.scrollTo({top:0,behavior:'smooth'})}
async function fetchJSON(url,timeout=10000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function getAuroraGrid(){if(auroraGrid&&Date.now()-auroraGrid.fetchedAt<NOAA_TTL)return auroraGrid;try{const d=await fetchJSON('https://services.swpc.noaa.gov/json/ovation_aurora_latest.json');auroraGrid={coords:d.coordinates||[],time:d['Forecast Time']||d['Observation Time'],fetchedAt:Date.now()};return auroraGrid}catch{return auroraGrid||{coords:[],time:null}}}
async function getSpaceWeather(){
	if(spaceWeather&&Date.now()-spaceWeather.fetchedAt<NOAA_TTL)return spaceWeather;
	const old=spaceWeather;
	const [kpResult,magResult]=await Promise.allSettled([
		fetchJSON('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json'),
		fetchJSON('https://services.swpc.noaa.gov/json/rtsw/rtsw_mag_1m.json')
	]);
	const kpRows=kpResult.status==='fulfilled'?kpResult.value:[];
	const magRows=magResult.status==='fulfilled'?magResult.value:[];
	const kpRow=kpRows.slice().reverse().find(r=>Number.isFinite(Number(r.Kp)))||kpRows.slice(1).reverse().find(r=>Number.isFinite(Number(r[1])));
	const bzOk=r=>r&&r.bz_gsm!=null&&Number.isFinite(Number(r.bz_gsm));
	const bzRow=magRows.find(r=>r.active===true&&bzOk(r))||magRows.find(bzOk)||magRows.slice(1).reverse().find(r=>Number.isFinite(Number(r[3])));
	spaceWeather={
		kp:kpRow?Number(kpRow.Kp??kpRow[1]):null,
		bz:bzRow?Number(bzRow.bz_gsm??bzRow[3]):null,
		time:bzRow?.time_tag||bzRow?.[0]||kpRow?.time_tag||kpRow?.[0],
		fetchedAt:Date.now()
	};
	// Gdy NOAA chwilowo nie odpowiada, zostawiamy poprzednie wartości zamiast pustych.
	if(old&&spaceWeather.kp==null)spaceWeather.kp=old.kp;
	if(old&&spaceWeather.bz==null)spaceWeather.bz=old.bz;
	return spaceWeather;
}
function auroraAt(lat,lon,grid){if(!grid.coords.length)return clamp((Math.abs(lat)-48)*2.2,0,45);let best=Infinity,val=0;const targetLon=lon<0?lon+360:lon;for(const p of grid.coords){const dLat=p[1]-lat,dLon=Math.min(Math.abs(p[0]-targetLon),360-Math.abs(p[0]-targetLon));const d=dLat*dLat+dLon*dLon;if(d<best){best=d;val=p[2]}}return Number(val)||0}
// Open-Meteo zwraca czas lokalny miejsca bez strefy. Czytamy go jako UTC, żeby wynik nie zależał od strefy przeglądarki.
const localMs=t=>Date.parse(t+'Z');
const localHM=ms=>new Date(ms).toISOString().slice(11,16);
function darknessAt(time,sunrise,sunset){const t=localMs(time),sr=localMs(sunrise),ss=localMs(sunset);return (t<sr||t>ss)?1:0.08}
async function reverseGeocode(lat,lon){try{const d=await fetchJSON(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${lat}&longitude=${lon}&localityLanguage=pl`);return {name:d.city||d.locality||d.principalSubdivision||'Twoja lokalizacja',country:d.countryName||''}}catch{return null}}
async function loadLocation(loc,{quiet=false}={}){const seq=++loadSeq;current=loc;if(!quiet){els.name.textContent=loc.name;els.coords.textContent=fmtCoords(loc.lat,loc.lon);els.status.textContent='Aktualizuję prognozę';els.score.textContent='—';renderPlaces()}try{const [weather,grid,space]=await Promise.all([fetchJSON(`https://api.open-meteo.com/v1/forecast?latitude=${loc.lat}&longitude=${loc.lon}&hourly=cloud_cover&daily=sunrise,sunset&current=cloud_cover&forecast_days=3&timezone=auto`),getAuroraGrid(),getSpaceWeather()]);if(seq!==loadSeq)return;renderForecast(loc,weather,grid,space);if(!els.mapView.hidden)showMap()}catch(e){if(seq!==loadSeq||quiet)return;els.status.textContent='Brak połączenia';els.quality.textContent='Spróbuj ponownie';els.summary.textContent='Nie udało się pobrać aktualnych danych. Sprawdź połączenie i odśwież stronę.'}}
function intensityColor(v){return v>=70?'#ff6d5a':v>=40?'#ffe45b':v>=18?'#b4ff63':'#52d9ba'}
async function showMap(){if(!window.L){els.mapNote.textContent='Mapa nie mogła się załadować. Sprawdź połączenie.';return}if(!map){map=L.map('auroraMap',{zoomControl:true,worldCopyJump:true}).setView(current?[current.lat,current.lon]:[65,18],3);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:8,attribution:'© OpenStreetMap'}).addTo(map)}setTimeout(()=>map.invalidateSize(),50);if(current){if(locationMarker)locationMarker.remove();locationMarker=L.circleMarker([current.lat,current.lon],{radius:7,color:'#fff',weight:2,fillColor:'#68f7bb',fillOpacity:1}).addTo(map).bindPopup(esc(current.name));if(mapLoc!==current){map.panTo([current.lat,current.lon]);mapLoc=current}}const grid=await getAuroraGrid();if(auroraLayer)auroraLayer.remove();auroraLayer=L.layerGroup().addTo(map);const renderer=L.canvas({padding:.5});let shown=0;for(let i=0;i<grid.coords.length;i+=3){const p=grid.coords[i],v=Number(p[2])||0;if(v<8)continue;let lon=p[0]>180?p[0]-360:p[0];L.circleMarker([p[1],lon],{renderer,radius:3+v/22,stroke:false,fillColor:intensityColor(v),fillOpacity:clamp(.22+v/120,.25,.82)}).addTo(auroraLayer);shown++}els.mapNote.textContent=shown?`Model NOAA OVATION • aktualizacja ${grid.time?new Date(grid.time).toLocaleString('pl-PL'):'bieżąca'}`:'Aktualnie model nie pokazuje wyraźnej aktywności.'}
function renderForecast(loc,w,grid,space){const offset=(w.utc_offset_seconds||0)*1000,nowLocal=Date.now()+offset,tz=w.timezone_abbreviation||'';const idx=w.hourly.time.findIndex(t=>localMs(t)>=nowLocal-1800000);const baseAurora=auroraAt(loc.lat,loc.lon,grid);const rows=[];for(let i=Math.max(0,idx);i<Math.min(w.hourly.time.length,idx+12);i++){const t=w.hourly.time[i],day=w.daily.time.findIndex(d=>t.startsWith(d));const dark=darknessAt(t,w.daily.sunrise[Math.max(0,day)],w.daily.sunset[Math.max(0,day)]);const cloud=w.hourly.cloud_cover[i];const latitudeBoost=clamp((Math.abs(loc.lat)-45)/25,0,1);const score=Math.round(clamp((baseAurora*.78+latitudeBoost*22)*dark*(1-cloud*.0075),0,99));rows.push({t,cloud,dark,score})}const first=rows[0]||{score:0,cloud:w.current?.cloud_cover||0,dark:.08};const best=rows.reduce((a,b)=>b.score>a.score?b:a,rows[0]||first);els.score.textContent=first.score;els.cloud.textContent=`${Math.round(first.cloud)}%`;els.activity.textContent=baseAurora<10?'Niska':baseAurora<35?'Umiarkowana':'Wysoka';els.dark.textContent=first.dark>.5?'Tak':'Nie';const userOffset=-new Date().getTimezoneOffset()*60000,diffH=(userOffset-offset)/3600000;els.updated.textContent=`Aktualizacja ${new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})}`;els.tzNote.hidden=diffH===0;els.tzNote.textContent=diffH===0?'':`Godziny według czasu miejsca (${tz}). U Ciebie jest o ${Math.abs(diffH).toLocaleString('pl-PL',{maximumFractionDigits:1})} h ${diffH>0?'później':'wcześniej'}.`;els.date.textContent=new Intl.DateTimeFormat('pl-PL',{weekday:'long',day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(nowLocal));const max=Math.max(...rows.map(r=>r.score));els.hourly.innerHTML=rows.map((r,i)=>`<div class="hour ${r.score===max&&max>10?'best':''}"><time>${i===0&&idx>=0?'Teraz':localHM(localMs(r.t))}</time><span class="weather">${r.dark>.5?(r.cloud>70?'☁':'☾'):'☀'}</span><strong>${r.score}%</strong><small>${r.cloud}% chmur</small></div>`).join('');renderGuidance(loc,best,baseAurora,space,grid,offset,diffH);renderVerdict(first,best,baseAurora)}
function renderGuidance(loc,best,activity,space,grid,offset=0,diffH=0){const start=best.t?localMs(best.t):NaN;els.bestWindow.textContent=best.dark<.5||!Number.isFinite(start)?'Po zachodzie słońca':`${localHM(start)}–${localHM(start+3600000)}`;const yourT=ms=>new Date(ms).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'});const yours=diffH!==0&&best.dark>=.5&&Number.isFinite(start)?` • u Ciebie ${yourT(start-offset)}–${yourT(start-offset+3600000)}`:'';els.viewMode.textContent=(best.score>=48?'Możliwa widoczność gołym okiem':best.score>=14?'Najpierw spróbuj aparatem':'Widoczność będzie ograniczona')+yours;const north=loc.lat>=0;els.directionText.textContent=north?'na północ':'na południe';els.directionArrow.textContent=north?'↑':'↓';els.kp.textContent=space.kp==null?'—':space.kp.toFixed(1);els.bz.textContent=space.bz==null?'—':space.bz.toFixed(1);const confidence=grid.coords.length&&space.kp!=null?'wysoka':grid.coords.length||space.kp!=null?'średnia':'niska';els.confidence.textContent=`Pewność prognozy: ${confidence} • wynik łączy aktywność, ciemność i chmury`;els.kp.dataset.value=space.kp??'';els.bz.dataset.value=space.bz??''}
function renderVerdict(first,best,activity){let status,verdict,reason,showWindow=false;if(activity<8&&best.score<10){status='Brak aktywności';verdict='Dziś zorzy nie zobaczysz';reason='Aktywność zorzowa jest zbyt niska dla Twojej lokalizacji.'}else if(first.dark<.5&&best.score>=10){status='Możliwa dziś w nocy';verdict='Zorza może być widoczna po zmroku';reason='Teraz jest za jasno. Poniżej pokazujemy najlepszy przewidywany przedział.';showWindow=true}else if(first.cloud>=75&&activity>=8){status='Zorza aktywna';verdict='Zorzę zasłaniają teraz chmury';reason=`Zachmurzenie wynosi ${Math.round(first.cloud)}%. Sprawdź późniejsze godziny.`;showWindow=best.score>=10}else if(first.score>=70){status='Bardzo dobre warunki';verdict='Wyjdź teraz — zorza jest aktywna';reason='Warunki sprzyjają obserwacji gołym okiem.';showWindow=true}else if(first.score>=40){status='Dobre warunki';verdict='Zorza może być widoczna gołym okiem';reason='Patrz w stronę wskazaną poniżej, z dala od świateł miasta.';showWindow=true}else if(first.score>=14){status='Zorza możliwa';verdict='Zorza może być widoczna przez aparat';reason='Gołym okiem może być bardzo słaba. Spróbuj trybu nocnego.';showWindow=true}else{status='Niska widoczność';verdict='Zorza jest aktywna, ale trudno ją teraz zobaczyć';reason=first.cloud>=50?'Przeszkodą jest duże zachmurzenie.':'Aktywność jest jeszcze zbyt słaba dla obserwacji gołym okiem.';showWindow=best.score>=10}els.status.textContent=status;els.verdict.textContent=verdict;els.summary.textContent=reason;els.tonightCard.hidden=!showWindow}
function explain(r,a){if(r.dark<.5)return 'Jest jeszcze jasno. Najlepsze szanse pojawią się po zachodzie słońca.';if(r.cloud>75)return 'Aktywność jest obserwowana, ale gęste chmury ograniczają widoczność.';if(a<10)return 'Niebo jest wystarczająco ciemne, jednak aktywność zorzowa pozostaje niska.';return 'Połączenie ciemnego nieba, aktywności zorzowej i zachmurzenia daje szansę na obserwację.'}
function renderPlaces(){const all=[...(current?.isGeo?[current]:[]),...saved];els.places.innerHTML=all.length?all.map((p,i)=>`<div class="place"><div class="place-main" data-i="${i}"><b>${esc(p.name)}</b><small>${esc(p.country||fmtCoords(p.lat,p.lon))}</small></div>${p.isGeo?'<span class="place-current">Bieżąca</span>':`<button class="delete-place" data-delete="${saved.indexOf(p)}" aria-label="Usuń ${esc(p.name)}">×</button>`}</div>`).join(''):'<p class="search-hint">Nie masz jeszcze dodatkowych miejsc.</p>';els.places.querySelectorAll('.place-main').forEach((b,i)=>b.onclick=()=>{loadLocation(all[i]);switchView('forecast')});els.places.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{saved.splice(+b.dataset.delete,1);store();renderPlaces();toast('Usunięto lokalizację')})}
async function search(q){els.hint.textContent='Szukam…';try{const d=await fetchJSON(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=8&language=pl&format=json`);const list=d.results||[];els.hint.textContent=list.length?'Wybierz miejsce z listy.':'Nie znaleziono takiego miejsca.';els.results.innerHTML=list.map((r,i)=>`<button class="result" data-i="${i}"><div><b>${esc(r.name)}</b><small>${esc([r.admin1,r.country].filter(Boolean).join(', '))}</small></div><span>＋</span></button>`).join('');els.results.querySelectorAll('.result').forEach(b=>b.onclick=()=>{const r=list[+b.dataset.i],p={name:r.name,country:r.country,lat:r.latitude,lon:r.longitude};if(!saved.some(x=>Math.abs(x.lat-p.lat)<.01&&Math.abs(x.lon-p.lon)<.01)){saved.push(p);store()}closeSheet();loadLocation(p);switchView('forecast');toast('Dodano lokalizację')})}catch{els.hint.textContent='Nie udało się wyszukać. Spróbuj ponownie.'}}
function locate(){if(!current)loadLocation(FALLBACK);const startSeq=loadSeq;if(!navigator.geolocation){toast('Lokalizacja jest niedostępna — pokazuję Szczecin');return}navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude,n=await reverseGeocode(lat,lon);if(loadSeq!==startSeq)return;loadLocation({name:n?.name||'Twoja lokalizacja',country:n?.country||'',lat,lon,isGeo:true})},()=>{toast('Brak dostępu do lokalizacji — pokazuję Szczecin')},{enableHighAccuracy:false,timeout:9000,maximumAge:900000})}
function openInfo(type){const kp=els.kp.dataset.value===''?NaN:Number(els.kp.dataset.value),bz=els.bz.dataset.value===''?NaN:Number(els.bz.dataset.value);if(type==='kp'){els.infoTitle.textContent='Indeks Kp';els.infoValue.textContent=Number.isFinite(kp)?kp.toFixed(1):'Brak danych';els.infoBody.textContent='Kp opisuje globalną aktywność geomagnetyczną w skali 0–9. Wyższa wartość zwykle oznacza możliwość zobaczenia zorzy dalej od biegunów, ale sama nie gwarantuje widoczności w Twoim miejscu.'}else{els.infoTitle.textContent='Pole magnetyczne Bz';els.infoValue.textContent=Number.isFinite(bz)?`${bz.toFixed(1)} nT`:'Brak danych';els.infoBody.textContent=Number.isFinite(bz)&&bz<0?'Bz jest skierowane na południe, co sprzyja przekazywaniu energii wiatru słonecznego do ziemskiej magnetosfery. Im dłużej pozostaje ujemne, tym lepiej dla zorzy.':'Ujemne Bz sprzyja powstawaniu zorzy. Dodatnia wartość zwykle ogranicza dopływ energii do ziemskiej magnetosfery.'}els.infoSheet.hidden=false;els.detailBackdrop.hidden=false}
function closeInfo(){els.infoSheet.hidden=true;els.detailBackdrop.hidden=true}
$('#addPlaceBtn').onclick=openSheet;$('#closeSearch').onclick=closeSheet;els.backdrop.onclick=closeSheet;$('#closeInfo').onclick=closeInfo;els.detailBackdrop.onclick=closeInfo;document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openInfo(b.dataset.detail));$('#locateBtn').onclick=()=>{locate();switchView('forecast')};$('#homeBtn').onclick=()=>switchView('forecast');$('#mapBtn').onclick=()=>switchView('map');$('#savedBtn').onclick=()=>switchView('places');els.input.oninput=e=>{clearTimeout(timer);const q=e.target.value.trim();if(q.length<2){els.results.innerHTML='';els.hint.textContent='Wpisz co najmniej 2 znaki.';return}timer=setTimeout(()=>search(q),350)};locate();renderPlaces();
// Co 5 minut odświeżamy prognozę i dane NOAA, gdy karta jest widoczna.
function refresh(){if(current&&!document.hidden)loadLocation(current,{quiet:true})}
setInterval(refresh,REFRESH_EVERY);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&auroraGrid&&Date.now()-auroraGrid.fetchedAt>=NOAA_TTL)refresh()});
